### ISSUE TITLE
Loose ends for v0.2 deployment

### ISSUE THREAD

**Issue by kenny-white** [cowri/cowri#22]
**Overview**
We are almost done with v0.2! There are a few loose ends remaining, this task is a list of outstanding tasks...

**Set-up guide/docs**
High level design or solution overview
- [x] John can you add tasks??
- [ ] Task 2

**Shell DAPP**
High level design or solution overview
- [x] Deploy new shell
- [ ] QA testing

**Crab Corner**
High level design or solution overview
- [ ] Tutorial docs
- [ ] publish Truffle box
- [ ] QA testing

**White paper**
High level design or solution overview
- [x] Finalize draft
- [x] everyone reads through it for typos
- [x] host on https url

**Comment by johnwhitton** [comment]
The following will be done by Wednesday
- [ ] Changes to shell @realisation 
- [ ] Rebuild and deploy (all to 2.0] (docker, npm and deploy) @Lastrellik 
- [ ] Developer Guide updated and Truffle Box deployed @juliusbuckley 

John Will
- [ ] Complete User Tutorial
- [ ] Complete Developer Setup Docker and Local
- [ ] Run Cowri Tutorial Solution
- [ ] Complete Cowri Crab Corner Solution
- [ ] Functional Validation (Minting and Multi-swap) Local and Kovan
